In [41]:
data1 = pd.read_excel(r"output.xlsx")
print(data1.head(5))

   Unnamed: 0                                            Comment  Sentiment
0           0     مقداد قداش مره تجيبوه افهمونا ماسط الشعب يحبوش          0
1           1             karim gharbi masit i sitcom ma3jibnich          0
2           2                                            mabldou          0
3           3  الهالكا مختصه قناه الزيتونه محايده وانتهت مهمت...          0
4           4  اتحاد الخراب والدمار خرب بلادنا يريدون افريقيا...          0


In [42]:
#data1.drop('Unnamed: 0', axis='columns', inplace=True)
data1

Unnamed: 0                                            Comment  \
0               0     مقداد قداش مره تجيبوه افهمونا ماسط الشعب يحبوش   
1               1             karim gharbi masit i sitcom ma3jibnich   
2               2                                            mabldou   
3               3  الهالكا مختصه قناه الزيتونه محايده وانتهت مهمت...   
4               4  اتحاد الخراب والدمار خرب بلادنا يريدون افريقيا...   
5               5             سلب لفلوسهم خاطر التوانسه فاقو بسرقتهم   
6               6             المءسسات الخاصه المصانع يشملهم الاضراب   
7               7                        مدخل المقروض الاضراب يامعلم   
8               8             والخاصه طز اخاطر يخلصو زوز فرنك السميك   
9               9                                  اتحاد الخراب ينجح   
10             10  اطمع يهز للهاويه بلاد شافه الافلاس والاتحاد هو...   
11             11  الاتحاد يتفاوظ الحكومه مداخيله الخاصه حل مشاكل...   
12             12                   تشخر زادت بوف يهلك التحاد الخراب   
13             13           مره ازيدنا كجيو القحوا اقلك نفاذ المخزون   
14             14  الكميه ناقصه مشطلع سومها الحمد لله مرضنا وبرين...   
15             15  تفدلك 6 ملاين تتحصل عامين اطيشها الزبله الشعب ...   
16             16                                         لقاح مشكوك   
17             17  الكلام تقول صحيح تمنيك الشعب اتصور خطابكم وكلا...   
18             18                                     بلاد تنتج الشر   
19             19    الغاز الماء يشملوا اطياف الشعب يهمهمش الخوانجيه   
20             20                                    وزير يركب المرض   
21             21                       akhmaj etayaran tunisair nul   
22             22  marra tisma33 7kaya jdida bled 7arfaa ken lmsa...   
23             23                     يهلكوو ماصيرو يتشد ماعندو هارب   
24             24                             lmohem tetlakch boulis   
25             25                                     عمله مسوده ذكي   
26             26                                     walah te7chmou   
27             27  الموظفين العمومين والنقابيين يتقاضون اجورا يقو...   
28             28   راجل كبير مانجم نحترم بياض شعرك ونمقط سواد وم...   
29             29                                            التفليم   
...           ...                                                ...   
10364       10364   deux domaines b3ad lezmek takhtar haja maghro...   
10365       10365   kenek parcours mte3ek maghrouma math info cot...   
10366       10366  wa9tha kammel domaine kenek maghrouma s v t su...   
10367       10367       sinon kenek belha9 dhay3a bin deux domaines    
10368       10368  akhtar thnia ashal a9sar médecine awel salaire...   
10369       10369  aandek concours résidanat yta3ab weli yejem ma...   
10370       10370  insat mpi ba3d 2 ans fama risque matekhouch br...   
10371       10371  khrouj barra médecine tokhrej lezmek t3adi con...   
10372       10372  sinon t9oss parcours mte3ek zone 4ème 5 ème an...   
10373       10373  par contre insat tejem tpostuli campus france ...   
10374       10374  yjewbouk haja rare tel9aha domainet okhra wya3...   
10375       10375  chouf l médecine lezem ta9ra 5 ans t3adi resid...   
10376       10376  beh kenik thebha vas hawka l 5edma sbitarat 7a...   
10377       10377  pour l ingénierie t5awelik ak4ar inik te5dem a...   
10378       10378  filo5er makich moula l moul te5dem 5edmtik to5...   
10379       10379   ak4ar mel medecine i9olik dentaire ena manins...   
10380       10380  عسلامه ينجم يعاوني يفسرلي نتعامل جدتي مريضه زه...   
10381       10381                        ouii taadi aand tbib o shay   
10382       10382    labes otlob nsaya7 kifeh yelzem tet3amlou m3aha   
10383       10383  lina3rfou lzm tsayerha 5ater ta3k3sha tod5el b...   
10384       10384        طريقه التعامل مهمه لازمها دواء ينقص الهلاوس   
10385       10385  ena jdati akaka lezm tsaysha 5atr mokhha mokh ...   
10386       10386  lezem thezouha l tbib fama dweyet inajem yaati...   
10387       10387  o ntouma tahkiw maaha tabda 

## STEP 4: Création du modèle de Machine Learning

In [43]:
# splitting the data into target and feature
feature = data1.Comment.fillna(' ')
target = data1.Sentiment
# splitting into train and tests
X_train, X_test, Y_train, Y_test = train_test_split(feature, target, test_size =.2, random_state=100)

In [ ]:
Y_train

In [ ]:
X_train

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(X_train)
# summarize
print(vectorizer.vocabulary_)
print(vectorizer.idf_)
# encode document
vector = vectorizer.transform([X_train[0]])
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

In [ ]:
vector1 = vectorizer.transform(X_train)
vector2 = vectorizer.transform(X_test)


In [ ]:
vector1

In [ ]:
X_train_modif=vector1.toarray()
X_test_modif=vector2.toarray()

In [ ]:
X_train_modif

In [ ]:
# make pipeline
from sklearn.metrics import precision_score, recall_score, accuracy_score
pipe = make_pipeline(LogisticRegression(solver='lbfgs',max_iter=10000))

In [ ]:
# make param grid
param_grid = {'logisticregression__C': [0.01, 0.1, 0.25, 0.75, 0.5, 1, 6,7,8,9,10,11,12,15,20, 100]}

# create and fit the model
model = GridSearchCV(pipe, param_grid, cv=5)
model.fit(X_train_modif,Y_train)

In [ ]:
predictions = model.predict(X_test_modif)

In [ ]:
# find accuracy, precision, recall:
from sklearn.metrics import confusion_matrix,classification_report
new = np.asarray(Y_test)
confusion_matrix(predictions,Y_test)

In [ ]:
print(classification_report(predictions,Y_test))

In [ ]:



# make prediction and print accuracy
prediction = model.predict(X_test_modif)
print(f"Accuracy score is {accuracy_score(Y_test, prediction):.2f}")
print(classification_report(Y_test, prediction))

precision = precision_score(Y_test, prediction, average='micro')
recall = recall_score(Y_test, prediction, average='micro')
accuracy = accuracy_score(Y_test, prediction)
print('Precision: {} / Recall: {} / Accuracy: {}'.format(round(precision, 3), round(recall, 3), round(accuracy, 3)))

In [ ]:
# make pipeline
from sklearn.metrics import precision_score, recall_score, accuracy_score
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score

param_C= [0.01, 0.1, 0.25, 0.75, 0.5, 1, 6,7,8,9,10,11,12,15,20, 100]
algo=['newton-cg', 'liblinear','sag','saga','lbfgs']
# create and fit the model

for c in param_C:
    for al in algo:
        pipe = make_pipeline(TfidfVectorizer(),
                    LogisticRegression(multi_class='multinomial', solver=al,C=c, max_iter=10000))
    #model = GridSearchCV(pipe,  cv=5)
    #model.fit(X_train,Y_train)
        model.fit(X_train_modif,Y_train)
        scores = cross_val_score(pipe, X_train_modif, Y_train, scoring='accuracy', cv=3, n_jobs=-1)
# report performance
        print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))
        #pipe.fit(X_train, Y_train)
        #print('Accuracy for C=%s: %s'
        # % (c, accuracy_score(Y_test, pipe.predict(X_test))))





# make prediction and print accuracy
#prediction = model.predict(X_test)
#print(f"Accuracy score is {accuracy_score(Y_test, prediction):.2f}")
#print(classification_report(Y_test, prediction))

#precision = precision_score(Y_test, prediction, average='micro')
#recall = recall_score(Y_test, prediction, average='micro')
#accuracy = accuracy_score(Y_test, prediction)
#print('Precision: {} / Recall: {} / Accuracy: {}'.format(round(precision, 3), round(recall, 3), round(accuracy, 3)))

### Random Forest Classifier

In [ ]:
#pipe = make_pipeline(TfidfVectorizer(),
#                    RandomForestClassifier())

#param_grid = {'randomforestclassifier__n_estimators':[10, 100, 1000],
  #           'randomforestclassifier__max_features':['sqrt', 'log2']}

#rf_model = GridSearchCV(pipe, param_grid, cv=5)
#rf_model.fit(X_train,Y_train)

#prediction = rf_model.predict(X_test)
#print(f"Accuracy score is {accuracy_score(Y_test, prediction):.2f}")

#precision = precision_score(Y_test, predictionة average='micro')
#recall = recall_score(Y_test, predictionة average='micro')
#accuracy = accuracy_score(Y_test, prediction)
#print('Precision: {} / Recall: {} / Accuracy: {}'.format(round(precision, 3), round(recall, 3), round(accuracy, 3)))

### Naive Bayes Classifier (Multinomial)

In [ ]:
#pipe = make_pipeline(TfidfVectorizer(),
            #        MultinomialNB())
#pipe.fit(X_train,Y_train)
#prediction = pipe.predict(X_test)
#print(f"Accuracy score is {accuracy_score(Y_test, prediction):.2f}")
#print(classification_report(Y_test, prediction))

### Support Vector Machine

In [ ]:
#pipe = make_pipeline(TfidfVectorizer(),
                   #  SVC())
#param_grid = {'svc__kernel': ['rbf', 'linear', 'poly'],
          ##   'svc__gamma': [0.1, 1, 10, 100],
          #   'svc__C': [0.1, 1, 10, 100]}

#svc_model = GridSearchCV(pipe, param_grid, cv=3)
#svc_model.fit(X_train, Y_train)

#prediction = svc_model.predict(X_test)
#print(f"Accuracy score is {accuracy_score(Y_test, prediction):.2f}")
#print(classification_report(Y_test, prediction))

### Tous les autres modèles

In [44]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
classifiers = [LinearSVC(), 
               SVC(gamma='auto'), 
               MultinomialNB(),
               LogisticRegression(solver='liblinear',max_iter=10000),
               BernoulliNB(), 
               SGDClassifier(), 
               DecisionTreeClassifier(max_depth=5),
               RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
               KNeighborsClassifier(3)
               ]

In [45]:
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix,classification_report
ngrams = (1, 2, 3)

results = []

for g in ngrams:
    #svc_model = GridSearchCV(pipe, param_grid, cv=3)
    #svc_model.fit(X_train, Y_train)

    #prediction = svc_model.predict(X_test)
    

    
    for alg in classifiers:
        pipeline = Pipeline([
        ('vect', TfidfVectorizer(min_df=0.0001, max_df=0.95,
                                 analyzer='word', lowercase=False,
                                 ngram_range=(1, g))),
        ('clf', alg), ])
        pipeline.fit(X_train, Y_train)
        feature_names = pipeline.named_steps['vect'].get_feature_names()
        prediction = pipeline.predict(X_test)
        print(f"**************************************")
        print(f"Classifier= "+str(alg)+" and the ngrams is= "+str(g))
        print(f"Accuracy score is {accuracy_score(Y_test, prediction):.2f}")
        print(classification_report(Y_test, prediction))
        # find accuracy, precision, recall:
        new = np.asarray(Y_test)
        print(confusion_matrix(prediction,Y_test))

**************************************
Classifier= LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0) and the ngrams is= 1
Accuracy score is 0.73
              precision    recall  f1-score   support

           0       0.68      0.58      0.63       516
           1       0.77      0.67      0.72       506
           2       0.81      0.80      0.81       517
           3       0.67      0.84      0.74       540

    accuracy                           0.73      2079
   macro avg       0.73      0.72      0.72      2079
weighted avg       0.73      0.73      0.72      2079

[[300  79  30  34]
 [ 74 340  10  19]
 [ 54   9 416  33]
 [ 88  78  61 454]]
**************************************
Classifier= SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='aut

C:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


**************************************
Classifier= MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True) and the ngrams is= 1
Accuracy score is 0.73
              precision    recall  f1-score   support

           0       0.58      0.65      0.62       516
           1       0.75      0.68      0.71       506
           2       0.79      0.83      0.81       517
           3       0.84      0.78      0.81       540

    accuracy                           0.73      2079
   macro avg       0.74      0.73      0.74      2079
weighted avg       0.74      0.73      0.74      2079

[[336 122  56  62]
 [ 82 343  16  18]
 [ 62  14 427  38]
 [ 36  27  18 422]]


C:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


**************************************
Classifier= LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False) and the ngrams is= 1
Accuracy score is 0.71
              precision    recall  f1-score   support

           0       0.66      0.55      0.60       516
           1       0.76      0.65      0.70       506
           2       0.81      0.77      0.79       517
           3       0.63      0.85      0.73       540

    accuracy                           0.71      2079
   macro avg       0.72      0.70      0.70      2079
weighted avg       0.71      0.71      0.70      2079

[[285  78  34  33]
 [ 70 328  16  18]
 [ 52  12 396  29]
 [109  88  71 460]]
**************************************
Classifier= BernoulliN

C:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


**************************************
Classifier= MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True) and the ngrams is= 2
Accuracy score is 0.74
              precision    recall  f1-score   support

           0       0.59      0.66      0.62       516
           1       0.76      0.68      0.72       506
           2       0.79      0.83      0.81       517
           3       0.84      0.78      0.81       540

    accuracy                           0.74      2079
   macro avg       0.74      0.74      0.74      2079
weighted avg       0.74      0.74      0.74      2079

[[340 122  54  61]
 [ 78 344  15  18]
 [ 62  14 430  40]
 [ 36  26  18 421]]


C:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


**************************************
Classifier= LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False) and the ngrams is= 2
Accuracy score is 0.71
              precision    recall  f1-score   support

           0       0.67      0.54      0.60       516
           1       0.76      0.66      0.71       506
           2       0.80      0.76      0.78       517
           3       0.62      0.85      0.72       540

    accuracy                           0.71      2079
   macro avg       0.72      0.70      0.70      2079
weighted avg       0.72      0.71      0.70      2079

[[280  72  30  33]
 [ 69 332  16  18]
 [ 54  13 395  29]
 [113  89  76 460]]
**************************************
Classifier= BernoulliN

C:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


**************************************
Classifier= KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform') and the ngrams is= 2
Accuracy score is 0.36
              precision    recall  f1-score   support

           0       0.74      0.13      0.22       516
           1       0.88      0.11      0.20       506
           2       0.90      0.20      0.32       517
           3       0.29      0.99      0.45       540

    accuracy                           0.36      2079
   macro avg       0.70      0.36      0.30      2079
weighted avg       0.70      0.36      0.30      2079

[[ 65  15   7   1]
 [  4  57   3   1]
 [  7   0 101   4]
 [440 434 406 534]]
**************************************
Classifier= LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_clas

C:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


**************************************
Classifier= MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True) and the ngrams is= 3
Accuracy score is 0.74
              precision    recall  f1-score   support

           0       0.59      0.66      0.62       516
           1       0.76      0.67      0.71       506
           2       0.78      0.83      0.81       517
           3       0.84      0.77      0.80       540

    accuracy                           0.74      2079
   macro avg       0.74      0.74      0.74      2079
weighted avg       0.74      0.74      0.74      2079

[[343 124  55  62]
 [ 73 341  15  19]
 [ 62  15 429  42]
 [ 38  26  18 417]]


C:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


**************************************
Classifier= LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False) and the ngrams is= 3
Accuracy score is 0.71
              precision    recall  f1-score   support

           0       0.68      0.54      0.60       516
           1       0.77      0.65      0.71       506
           2       0.80      0.76      0.78       517
           3       0.62      0.86      0.72       540

    accuracy                           0.71      2079
   macro avg       0.72      0.70      0.70      2079
weighted avg       0.72      0.71      0.70      2079

[[279  71  31  31]
 [ 67 331  17  16]
 [ 56  14 395  31]
 [114  90  74 462]]
**************************************
Classifier= BernoulliN

C:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


**************************************
Classifier= KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform') and the ngrams is= 3
Accuracy score is 0.35
              precision    recall  f1-score   support

           0       0.75      0.12      0.20       516
           1       0.89      0.11      0.20       506
           2       0.90      0.16      0.28       517
           3       0.29      0.99      0.45       540

    accuracy                           0.35      2079
   macro avg       0.71      0.35      0.28      2079
weighted avg       0.70      0.35      0.28      2079

[[ 61  13   6   1]
 [  3  56   3   1]
 [  7   0  85   2]
 [445 437 423 536]]
